bookmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmarks/', include('homepage.urls')),

    path('', RedirectView.as_view(url="bookmarks/", permanent=True)),

    # path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homepage/urls.py
from django.urls import path
from homepage import views

urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new_update_bookmark, name="new-bookmark"),

    path('<int:pk>/update/', views.new_update_bookmark, name="update-bookmark"),

    path('<int:pk>/deleted/', views.delete_bookmark, name="delete-bookmark"),

    path('<int:b_id>/copy-to/<int:f_id>/', views.copy_to_folder, name="copy-to-folder"),

    path('search/', views.search, name="search"),

    path('folder/<int:id>/', views.display_folder_content, name="folder-content"),

    path('folder/rename/<int:id>/', views.folder_rename, name="folder-rename"),

    path('folder/<int:id>/delete/', views.folder_delete, name="folder-delete"),

    path('folder/new/', views.new_folder, name="new-folder"),

    path('view/<int:id>/', views.view_bookmark, name="view-bookmark"),



]

homepage/models.py
from django.db import models
from taggit.managers import TaggableManager


class Folder(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)

    def __str__(self):
        return self.name


class Bookmark(models.Model):
    name = models.CharField(max_length=200, default=None, blank=True)
    folder_name = models.ForeignKey(Folder, on_delete=models.SET_NULL, null=True)
    url = models.URLField(max_length=230, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    tags = TaggableManager()

    def __str__(self):
        return f"{self.name} - {self.url}"

homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from homepage.models import Bookmark, Folder


def index(request):
    bookmarks = Bookmark.objects.filter(folder_name=None).order_by('-timestamp')

    folders = Folder.objects.all()
    params = {
        'bookmarks': bookmarks,
        'folders': folders,
    }
    return render(request, 'homepage/index.html', params)


def new_update_bookmark(request, pk=None):

    if request.method == 'POST':

        name = request.POST['name']
        description = request.POST['description']
        url = request.POST['url']
        tags = request.POST['tags']
        sent_to_folder = request.POST.get('sent_to_folder')

        folder_obj = None
        if not sent_to_folder is None:
            folder_obj = Folder.objects.get(name=sent_to_folder)

        tag_list = tags.split(',')
        if request.POST.get("new") == "new":
            bookmark_obj = Bookmark(name=name, url=url, folder_name=folder_obj, description=description)
            bookmark_obj.save()
            for tag in tag_list:
                bookmark_obj.tags.add(tag)
            bookmark_obj.save()
            messages.success(request, f"Your bookmark '{name}' has been successfully created.")
            return redirect('index')

        if request.POST.get("update") == "update":
            bookmark_obj = Bookmark.objects.get(pk=pk)
            bookmark_obj.name = name
            bookmark_obj.description = description
            bookmark_obj.url = url
            bookmark_obj.folder_name = folder_obj

            for tag in tag_list:
                bookmark_obj.tags.add(tag)

            bookmark_obj.save()

        messages.success(request, f"Your bookmark '{bookmark_obj.name}' has been successfully updated.")
        return redirect('index')

    else:
        return HttpResponse("<h1>Get request not available</h1>")


def delete_bookmark(request, pk):
    if request.method == "POST":
        bookmark_obj = Bookmark.objects.get(pk=pk)
        bookmark_obj.delete()
        messages.warning(request, f"Your bookmark was successfully deleted.")
        return redirect('index')


def search(request):
    if request.method == 'GET':
        search_query = request.GET['search']
        bookmark_search = Bookmark.objects.filter(name__icontains=search_query)
        params = {
            'searches': bookmark_search,
            'search_query': search_query,
        }
        return render(request, 'homepage/search.html', params)


def copy_to_folder(request, b_id=None, f_id=None):
    bookmark_id = Bookmark.objects.get(id=b_id)
    bookmark_id.folder_name = Folder.objects.get(id=f_id)
    bookmark_id.save()
    messages.success(request, f"Your bookmark was successfully sent to '{bookmark_id.folder_name}'.")
    return redirect('index')


def display_folder_content(request, id):
    folder_object = Folder.objects.get(id=id)
    bookmark_object = Bookmark.objects.filter(folder_name=folder_object)
    params = {
        'bookmarks': bookmark_object,
        'folders': Folder.objects.all(),
        'folder_name': folder_object.name,
    }

    return render(request, 'homepage/display_folder_content.html', params)


def folder_rename(request, id):
    if request.method == 'POST':
        folder_obj = Folder.objects.get(id=id)
        folder_obj.name = request.POST['name']
        folder_obj.save()
        messages.success(request, f"Your bookmark folder was successfully renamed.")
        return redirect('index')


def folder_delete(request, id):
    folder_delete_object = Folder.objects.get(id=id)
    deleted_folder_name = folder_delete_object.name
    bookmark_objects_to_delete = Bookmark.objects.filter(folder_name=folder_delete_object)
    folder_delete_object.delete()

    for bookmark in bookmark_objects_to_delete:
        bookmark.delete()
    messages.warning(request, f"Your bookmark folder '{deleted_folder_name}' was successfully deleted.")
    return redirect('index')


def new_folder(request):
    if request.method == 'POST':
        new_folder_name = request.POST['name']
        folder_object = Folder(name=new_folder_name)
        folder_object.save()
        messages.success(request, f"Folder '{new_folder_name}' was successfully created.")
        return redirect('index')


def view_bookmark(request, id):
    bookmark_obj = Bookmark.objects.get(id=id)
    params = {
        'bookmark': bookmark_obj,
    }

    return render(request, 'homepage/view_bookmark.html', params)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="expires" content="-1"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
    <style>
        .footer {
            position: fixed;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }

        a {
            text-decoration: none;
        }

        body {
            font-size: 18px;
        }

        html, body {
            height: 100%
        }
        {% block style %}{% endblock %}</style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg p-1 navbar-light bg-light" style="border:1px dotted lightgrey">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">DoBookmark</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <form class="d-flex" action="{% url 'search' %}" method="get">
                    <input class="form-control me-2" name="search" type="search" placeholder="Search"
                           aria-label="Search">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
            </ul>

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <div class="dropdown">
                    <button class="border-0 bg-light" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        More <i class="fa fa-chevron-down" aria-hidden="true"></i>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li>
                            <button data-bs-toggle="modal" data-bs-target="#staticBackdrop" class="dropdown-item"
                                    href="#">New bookmark
                            </button>
                        </li>
                        <li>
                            <button data-bs-toggle="modal" data-bs-target="#newfolder" class="dropdown-item"
                                    href="#">New Folder
                            </button>
                        </li>

                        <li><a class="dropdown-item" href="#">Help center</a></li>
                    </ul>
                </div>
            </ul>


        </div>
    </div>
</nav>


{#New folder#}
<div class="modal fade" id="newfolder" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header p-2">
                <h5 class="modal-title pl-2" id="staticBackdropLabel">New folder</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'new-folder' %}" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="mb-1">
                            <label for="exampleFormControlInput1" class="form-label"><i class="fa fa-folder"
                                                                                        aria-hidden="true"></i>
                                Name</label>
                            <input type="text" class="form-control" name="name" id="exampleFormControlInput1"
                                   placeholder="Enter folder name">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn-sm btn btn-secondary" data-bs-dismiss="modal">Close
                        </button>
                        <button type="submit" name="new" value="new" class="btn-sm btn btn-primary">Create</button>
                    </div>
                </form>

            </div>
        </div>

    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header p-2">
                <h5 class="modal-title pl-2" id="staticBackdropLabel">Add a bookmark</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'new-bookmark' %}" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="mb-1">
                            <label for="exampleFormControlInput1" class="form-label">Name</label>
                            <input type="text" class="form-control" name="name" id="exampleFormControlInput1"
                                   placeholder="Enter name of the bookmark">
                        </div>
                        <div class="mb-1">
                            <label for="exampleFormControlInput2" class="form-label">URL</label>
                            <input type="text" class="form-control" name="url" id="exampleFormControlInput2"
                                   placeholder="Eg. domain.com, URL for new bookmark">
                        </div>
                        <div class=" mb-3">
                            <label for="exampleFormControlTextarea3" class="form-label">Description</label>
                            <textarea class="form-control" placeholder="Enter the description of your bookmark"
                                      name="description" id="exampleFormControlTextarea3"
                                      rows="3"></textarea>
                        </div>

                        <label class="form-label" for="id_folder_name">Send bookmark to (Optional)</label>
                        <select class="mb-3 form-control" id="id_folder_name" name="sent_to_folder">
                            <option selected disabled>Select folder</option>
                            {% for folder in folders %}
                                <option value="{{ folder }}">{{ folder }}</option>
                            {% endfor %}

                        </select>

                        <div class=" mb-3">
                            <label for="exampleFormControlTextarea4" class="form-label">Tags</label>
                            <input class="form-control" placeholder="Enter the description of your bookmark"
                                   name="tags" id="Enter tags seprated by a comma.">
                        </div>


                        <div class="modal-footer">
                            <button type="button" class="btn-sm btn btn-secondary" data-bs-dismiss="modal">Close
                            </button>
                            <button type="submit" name="new" value="new" class="btn-sm btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>

    </div>
</div>

<div class="container">
    <div class="row mt-4">
        <div class="col-lg-2  col-md-2 col-sm-12">
        </div>

        <div class="col-lg-8 col-lg-8 md-12 col-md-12 col-sm-12">

            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}


            {% block body %}{% endblock %}
        </div>
    </div>
</div>

<br><br><br>
<br><br><br>
<footer class="footer navbar-fixed-bottom">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-dark" href="https://bookmarks14.herokuapp.com">bookmarks.com</a>
    </div>
    <!-- Copyright -->
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
</body>
</html>

templates/homepage/display_folder_content.html
{% extends 'base.html' %}

{% block title %}Homepage - DoBookmarks{% endblock %}

{% block body %}
    <h1>{{ bookmark.folder_name }}</h1>
    <div class="mt-4"></div>

    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
         aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ folder_name }}</li>
        </ol>
    </nav>
    <div class="alert border border" role="alert">

        {% if bookmarks %}
            {% for bookmark in bookmarks %}
                <div class="col-md-12 d-flex border-bottom p-2 justify-content-between">

                    <div class="col-md-11">
                        <a href="http://{{ bookmark.url }}/"><i class="fa fa-file"
                                                                style="color: #6f94c6; font-size: 21px; padding-right: 1%;"
                                                                aria-hidden="true"></i> {{ bookmark.name }}</a>
                        {% for tag in bookmark.tags.all %}
                            <span class="badge bg-primary">{{ tag }}</span>
                        {% endfor %}
                    </div>
                    <div class="col-md-1">
                        <button class="btn btn-sm" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                            <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'view-bookmark' bookmark.id %}" class="dropdown-item">
                                View details
                            </a>
                            </li>
                            <li><a class="dropdown-item" data-bs-target="#edit-{{ forloop.counter }}"
                                   data-bs-toggle="modal">
                                Edit
                            </a></li>
                            <li><a class="dropdown-item" data-bs-target="#delete-{{ forloop.counter }}"
                                   data-bs-toggle="modal">
                                Delete
                            </a></li>



                            {% if folders %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a style="color: darkgrey;" class="dropdown-item"
                                       data-bs-target="#delete-{{ forloop.counter }}"
                                       data-bs-toggle="modal">
                                    Send to <i class="fa fa-arrow-down" aria-hidden="true"></i>
                                </a></li>
                            {% endif %}
                            {% for folder in folders %}
                                <li><a class="dropdown-item"
                                       href="{% url 'copy-to-folder' bookmark.id folder.id %}">
                                    {{ folder.name|truncatechars:'50' }}
                                </a></li>
                            {% endfor %}
                        </ul>
                    </div>


                    <!-- Modal EDIT-->
                    <div class="modal fade" id="edit-{{ forloop.counter }}" data-bs-backdrop="static"
                         data-bs-keyboard="false"
                         tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Update your bookmark here</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'update-bookmark' bookmark.id %}" method="post">
                                        {% csrf_token %}
                                        <div class="mb-1">
                                            <label for="exampleFormControlInput1" class="form-label">Name</label>
                                            <input type="text" class="form-control" value="{{ bookmark.name }}"
                                                   name="name"
                                                   id="exampleFormControlInput1"
                                                   placeholder="Enter name of the bookmark">
                                        </div>
                                        <div class="mb-1">
                                            <label for="exampleFormControlInput2" class="form-label">URL</label>
                                            <input type="text" class="form-control" value="{{ bookmark.url }}"
                                                   name="url"
                                                   id="exampleFormControlInput2"
                                                   placeholder="Enter URL for new bookmark">
                                        </div>
                                        <div class=" mb-3">
                                            <label for="exampleFormControlTextarea3"
                                                   class="form-label">Description</label>
                                            <textarea class="form-control"
                                                      placeholder="Enter the description of your bookmark"
                                                      name="description" id="exampleFormControlTextarea3"
                                                      rows="3">{{ bookmark.description }}</textarea>
                                        </div>

                                        <div class=" mb-3">
                                            <label for="exampleFormControlTextarea4" class="form-label">Tags</label>
                                            <input class="form-control"
                                                   value="{% for tag in bookmark.tags.all %}{{ tag }},{% endfor %}"
                                                   placeholder="Enter the description of your bookmark"
                                                   name="tags" id="Enter tags seprated by a comma.">
                                        </div>

                                        <div class="modal-footer">
                                            <button type="button" class="btn-sm btn btn-secondary"
                                                    data-bs-dismiss="modal">Close
                                            </button>
                                            <button type="submit" name="update" value="update"
                                                    class="btn-sm btn btn-primary">Save
                                            </button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>

                    <!--  MODAL DELETE -->
                    <div class="modal fade" id="delete-{{ forloop.counter }}" data-bs-backdrop="static"
                         data-bs-keyboard="false"
                         tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Delete this bookmark?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete this bookmark?</p>
                                    <div class="modal-footer">
                                        <button type="button" class="btn-sm btn btn-secondary"
                                                data-bs-dismiss="modal">Close
                                        </button>
                                        <form action="{% url 'delete-bookmark' bookmark.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" name="delete" value="delete"
                                                    class="btn-sm btn btn-primary">Delete
                                            </button>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            {% endfor %}
        {% else %}
            <p>No bookmark added. To add a bookmark,
                <a data-bs-target="#staticBackdrop" data-bs-toggle="modal"
                   href="#">click here
                </a>.</p>
        {% endif %}
    </div>

{% endblock %}

templates/homepage/update_bookmark.html
{% extends 'base.html' %}

{% block title %}Homepage - DoBookmarks{% endblock %}

{% block body %}
    <h1>Welcome to DoBookmarks. Go ahead and update <br>'{{ update_bookmark.description }}'.</h1>
    <div class="mt-4"></div>

    <div class="alert border border-primary" role="alert">
        <div class="col-md-12 d-flex border-bottom p-2 justify-content-between">
            <span> </span>
            <button class="btn btn-outline border btn-sm" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Edit</a></li>
                <li><a class="dropdown-item" href="#">Delete</a></li>
            </ul>
        </div>
        <form action="{% url 'new-bookmark' %}" method="post">
                {% csrf_token %}
                <div class="container">
                    {% for field in form.visible_fields %}
                        <tr>
                            <th>{{ field.label_tag }}</th>
                            <td>
                                {{ field.errors }}<br>
                                {{ field }}<br>
                                {{ field.help_text }}<br>
                            </td>
                        </tr>
                    {% endfor %}
                </div>


                <div class="modal-footer mt-3">
                    <button type="button" class="btn-sm btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn-sm btn btn-primary">Save</button>
                </div>
            </form>


    </div>
    <script type="text/javascript">
    $(window).on('load', function() {
        $('#new_bookmark').modal('show');
    });
</script>
{% endblock %}

templates/homepage/view_bookmark.html
{% extends 'base.html' %}

{% block title %}Homepage - DoBookmarks{% endblock %}

{% block body %}
    <h1>Welcome to DoBookmarks. Now create, view, delete, put to folders; your bookmarks.</h1>
    <div class="mt-4"></div>

    <div class="alert border border" role="alert">

        <div class="col-md-12 d-flex border-bottom p-2 justify-content-between">

            <div class="col-md-9">
                <a href="#"><i class="fa fa-file" style="color: #6f94c6; font-size: 21px; padding-right: 1%;"
                               aria-hidden="true"></i> {{ bookmark.name }}</a></div>
            <div class="col-md-3">
                {{ bookmark.timestamp }}
            </div>

        </div>

        <strong>URL:</strong><br>
        <a href="{{ bookmark.url }}">{{ bookmark.url }}</a><br>
<br>
        <strong>Description:</strong>
        <p>{{ bookmark.description }}</p>

        <strong>Tags:</strong><br>
        {% for tag in bookmark.tags.all %}
            <span class="badge bg-primary">{{ tag }}</span>
        {% endfor %}
    </div>

    <!-- Modal -->
    <div class="modal edit_bookmark fade" id="edit_model" data-bs-backdrop="static" data-bs-keyboard="false"
         tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header p-2">
                    <h5 class="modal-title pl-2" id="staticBackdropLabel">Add a bookmark</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'new-bookmark' %}" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="mb-1">
                            <label for="exampleFormControlInput1" class="form-label">Name</label>
                            <input type="text" class="form-control" name="name" id="exampleFormControlInput1"
                                   placeholder="Enter name of the bookmark">
                        </div>
                        <div class="mb-1">
                            <label for="exampleFormControlInput2" class="form-label">URL</label>
                            <input type="text" class="form-control" name="url" id="exampleFormControlInput2"
                                   placeholder="Enter URL for new bookmark">
                        </div>
                        <div class=" mb-3">
                            <label for="exampleFormControlTextarea3" class="form-label">Description</label>
                            <textarea class="form-control" placeholder="Enter the description of your bookmark"
                                      name="description" id="exampleFormControlTextarea3"
                                      rows="3"></textarea>
                        </div>

                        <div class=" mb-3">
                            <label for="exampleFormControlTextarea4" class="form-label">Tags</label>
                            <input class="form-control" placeholder="Enter the description of your bookmark"
                                   name="tags" id="Enter tags seprated by a comma.">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn-sm btn btn-secondary" data-bs-dismiss="modal">Close
                            </button>
                            <button type="submit" name="update" class="btn-sm btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>


            </div>

        </div>
    </div>

{% endblock %}